name: .NET CI/CD Pipeline to IIS

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: msbuild -t:Restore -p:Configuration=Release website.publishproj
      working-directory: ./

    - name: Build Project
      run: msbuild -p:Configuration=Release -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:SkipInvalidConfigurations=true website.publishproj
      working-directory: ./

    - name: Test Project
      run: |
        # Replace with the actual command to run your tests, e.g., using dotnet test
        echo "Run your tests command here"
      working-directory: ./

    - name: Create Artifact
      run: |
        mkdir artifact
        Copy-Item -Path '$(Get-Item website.publishproj -p:PackageAsSingleFile=true -p:SkipInvalidConfigurations=true -p:Configuration=Release -p:WebPublishMethod=Package -p:PackageLocation=artifact)' -Destination 'artifact'
      working-directory: ./

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: artifact

    - name: Deploy to IIS
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: ./artifact/*
        target: 'c:/inetpub/wwwroot/'
