name: .NET Framework CI/CD Pipeline to AWS Windows Instance

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: msbuild -t:Restore -p:Configuration=Release ./bis/website.publishproj

    - name: Build Project
      run: msbuild -p:Configuration=Release -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:SkipInvalidConfigurations=true -p:OutputPath=.PublishOutput ./bis/website.publishproj


      #    - name: List output directory
      #      run: ls -la ./PublishOutput
      #      shell: pwsh

    - name: Test Project
      run: |
        # Replace with the actual command to run your tests, e.g., using VSTest
        echo "Run your tests command here"

    - name: Publish Project
      run: msbuild -p:Configuration=Release -p:DeployOnBuild=true -p:OutputPath=./PublishOutput ./bis/website.publishproj


    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts-01
        path: ./PublishOutput/**

        #    - name: Deploy to AWS Windows Instance via SCP
        #      run: |
        #        choco install openssh -y
        #        scp -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -P 22 -o StrictHostKeyChecking=no -r ./PublishOutput/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/inetpub/wwwroot/
        #      shell: pwsh
        #
        #    - name: Restart IIS
        #      run: |
        #        ssh -i ${{ secrets.SSH_PRIVATE_KEY_PATH }} -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "iisreset"
        #      shell: pwsh
        #
        #env:
        #  SSH_PRIVATE_KEY_PATH: ${{ secrets.SSH_PRIVATE_KEY }}
        #  USERNAME: ${{ secrets.SERVER_USERNAME }}
        #  HOST: ${{ secrets.SERVER_ADDRESS }}
